<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>Test config_func_error_1_SUITE:exit_in_iptc result</title>
<meta http-equiv="cache-control" content="no-cache"></meta>
<meta http-equiv="content-type" content="text/html; charset=utf-8"></meta>
<link rel="stylesheet" href="../../ct_default.css" type="text/css"></link>
<script type="text/javascript" src="../../jquery-latest.js"></script>
<script type="text/javascript" src="../../jquery.tablesorter.min.js"></script>
</head>
<body>

<a name="top"></a><pre>
=== Test case: <a href="config_func_error_1_suite.src.html#exit_in_iptc-1">config_func_error_1_SUITE:exit_in_iptc/1</a> (click for source code)

=== Config value:

    [{watchdog,&lt;0.3815.0&gt;},
     {tc_logfile,"/buildroot/otp/lib/common_test/make_test_dir/ct_logs/ct_run.test_server@a46a33ecc1a5.2024-10-16_11.40.24/make_test_dir.common_test_test.logs/run.2024-10-16_11.40.27/log_private/ct_run.ct@a46a33ecc1a5.2024-10-16_11.52.02/ct_error_SUITE_data.error.config_func_error_1_SUITE.logs/run.2024-10-16_11.52.02/config_func_error_1_suite.exit_in_iptc.html"},
     {tc_group_properties,[]},
     {tc_group_path,[]},
     {data_dir,"/buildroot/otp/lib/common_test/make_test_dir/common_test_test/ct_error_SUITE_data/error/test/config_func_error_1_SUITE_data/"},
     {priv_dir,"/buildroot/otp/lib/common_test/make_test_dir/ct_logs/ct_run.test_server@a46a33ecc1a5.2024-10-16_11.40.24/make_test_dir.common_test_test.logs/run.2024-10-16_11.40.27/log_private/ct_run.ct@a46a33ecc1a5.2024-10-16_11.52.02/ct_error_SUITE_data.error.config_func_error_1_SUITE.logs/run.2024-10-16_11.52.02/log_private/"}]

=== Current directory is "/buildroot/otp/lib/common_test/make_test_dir/ct_logs/ct_run.test_server@a46a33ecc1a5.2024-10-16_11.40.24/make_test_dir.common_test_test.logs/run.2024-10-16_11.40.27/log_private/ct_run.ct@a46a33ecc1a5.2024-10-16_11.52.02"

=== Started at 2024-10-16 11:52:02

<br />
ct_test_support *returning* error of type 'BADMATCH'

</pre>
<div class="default"><pre><b>*** User 2024-10-16 11:52:02.986 ***</b><a id=e-1 class="link-to-entry" href="#e-1">&#x1f517;</a>
Bye bye from &lt;0.3818.0&gt;
</pre></div>
<pre>

</pre>
<div class="default"><pre><b>*** User 2024-10-16 11:52:02.986 ***</b><a id=e-2 class="link-to-entry" href="#e-2">&#x1f517;</a>
Calling error fun now...
</pre></div>
<pre>

</pre>
<div class="sasl"><pre><b>*** System report during config_func_error_1_SUITE:exit_in_iptc/1 2024-10-16 11:52:02.986 ***</b><a id=e-3 class="link-to-entry" href="#e-3">&#x1f517;</a>
=ERROR REPORT==== 16-Oct-2024::11:52:02.986680 ===
Error in process &lt;0.3818.0&gt; on node ct@a46a33ecc1a5 with exit value:
{{badmatch,undefined},
 [{ct_test_support,'-random_error/1-fun-2-',2,
                   [{file,"ct_test_support.erl"},{line,440}]},
  {config_func_error_1_SUITE,bad_proc,1,
                             [{file,"config_func_error_1_SUITE.erl"},
                              {line,81}]}]}


</pre></div>
<pre>
=== ERROR! config_func_error_1_SUITE:init_per_testcase(exit_in_iptc, [{watchdog,
                                                                   &lt;0.3817.0&gt;},
                                                                  {tc_logfile,
                                                                   "/buildroot/otp/lib/common_test/make_test_dir/ct_logs/ct_run.test_server@a46a33ecc1a5.2024-10-16_11.40.24/make_test_dir.common_test_test.logs/run.2024-10-16_11.40.27/log_private/ct_run.ct@a46a33ecc1a5.2024-10-16_11.52.02/ct_error_SUITE_data.error.config_func_error_1_SUITE.logs/run.2024-10-16_11.52.02/config_func_error_1_suite.exit_in_iptc.html"},
                                                                  {tc_group_properties,
                                                                   []},
                                                                  {tc_group_path,
                                                                   []},
                                                                  {data_dir,
                                                                   "/buildroot/otp/lib/common_test/make_test_dir/common_test_test/ct_error_SUITE_data/error/test/config_func_error_1_SUITE_data/"},
                                                                  {priv_dir,
                                                                   "/buildroot/otp/lib/common_test/make_test_dir/ct_logs/ct_run.test_server@a46a33ecc1a5.2024-10-16_11.40.24/make_test_dir.common_test_test.logs/run.2024-10-16_11.40.27/log_private/ct_run.ct@a46a33ecc1a5.2024-10-16_11.52.02/ct_error_SUITE_data.error.config_func_error_1_SUITE.logs/run.2024-10-16_11.52.02/log_private/"}]) failed!
	Reason: {'EXIT',{badmatch,undefined}}

<a name="end"></a>


=== Ended at 2024-10-16 11:52:03
=== Location: {ct_test_support,'-random_error/1-fun-2-',440}
=== Reason: init_per_testcase failed
</pre>
<center>
<br /><hr /><p>
<a href="../../../all_runs.html">Test run history
</a>  |  <a href="../../../index.html">Top level test index
</a>  |  <a href="../../../suite.log.latest.html">Latest test result</a>
</p>
<div class="copyright">Copyright &copy; 2024 <a href="http://www.erlang.org">Open Telecom Platform</a><br />
Updated: <!--date-->Wed Oct 16 2024 11:52:02<!--/date--><br />
</div>
</center>
</body>
</html>
